# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-08 18:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170708_2307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='votes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='votes',
        ),
    ]
